<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6Sb1YKs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6Sb1YKs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6Sb1YKs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6Sb1YKs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6Sb1YKs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6Sb1YKs',
    'container.build_id' => 'fb145da3',
    'container.build_time' => 1646827563,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6Sb1YKs');
