<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPXRV8rt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPXRV8rt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPXRV8rt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPXRV8rt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPXRV8rt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PXRV8rt',
    'container.build_id' => 'df2c7670',
    'container.build_time' => 1646837781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPXRV8rt');
