<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCg3UvxJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCg3UvxJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCg3UvxJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCg3UvxJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCg3UvxJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Cg3UvxJ',
    'container.build_id' => '94327959',
    'container.build_time' => 1644784203,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCg3UvxJ');
