<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1wt5TYx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1wt5TYx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1wt5TYx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1wt5TYx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1wt5TYx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1wt5TYx',
    'container.build_id' => '5cd6c68e',
    'container.build_time' => 1644875372,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1wt5TYx');
