<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF8xM139\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF8xM139/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF8xM139.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF8xM139\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF8xM139\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F8xM139',
    'container.build_id' => '26164fe2',
    'container.build_time' => 1646348316,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF8xM139');
