<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \App\Entity\Post implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'DescriptionP', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'HashtagP', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'DateP', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'Likes', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'Client', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'commentaires', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'visibilite', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'ImageP'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'DescriptionP', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'HashtagP', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'DateP', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'Likes', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'Client', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'commentaires', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'visibilite', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'ImageP'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Post $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionP(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionP', []);

        return parent::getDescriptionP();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionP(string $DescriptionP): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionP', [$DescriptionP]);

        return parent::setDescriptionP($DescriptionP);
    }

    /**
     * {@inheritDoc}
     */
    public function getHashtagP(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHashtagP', []);

        return parent::getHashtagP();
    }

    /**
     * {@inheritDoc}
     */
    public function setHashtagP(?string $HashtagP): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHashtagP', [$HashtagP]);

        return parent::setHashtagP($HashtagP);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateP(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateP', []);

        return parent::getDateP();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateP(\DateTimeInterface $DateP): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateP', [$DateP]);

        return parent::setDateP($DateP);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisibilite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisibilite', []);

        return parent::getVisibilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisibilite(string $visibilite): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisibilite', [$visibilite]);

        return parent::setVisibilite($visibilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageP(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageP', []);

        return parent::getImageP();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageP(?string $ImageP): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageP', [$ImageP]);

        return parent::setImageP($ImageP);
    }

    /**
     * {@inheritDoc}
     */
    public function getLikes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLikes', []);

        return parent::getLikes();
    }

    /**
     * {@inheritDoc}
     */
    public function addLike(\App\Entity\PostLike $like): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLike', [$like]);

        return parent::addLike($like);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLike(\App\Entity\PostLike $like): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLike', [$like]);

        return parent::removeLike($like);
    }

    /**
     * {@inheritDoc}
     */
    public function nblike()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nblike', []);

        return parent::nblike();
    }

    /**
     * {@inheritDoc}
     */
    public function getClient(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(?\App\Entity\User $Client): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$Client]);

        return parent::setClient($Client);
    }

    /**
     * {@inheritDoc}
     */
    public function isLikeByUser(\App\Entity\User $Client): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLikeByUser', [$Client]);

        return parent::isLikeByUser($Client);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', []);

        return parent::getCommentaires();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentaire(\App\Entity\Commentaire $commentaire): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentaire', [$commentaire]);

        return parent::addCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommentaire(\App\Entity\Commentaire $commentaire): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommentaire', [$commentaire]);

        return parent::removeCommentaire($commentaire);
    }

}
